x = "Hello World"	#str	
x1 = 20	#int	
x2 = 20.5	#float	
x3 = 1j	#complex	
x4 = ["apple", "banana", "cherry"]	#list	
x5 = ("apple", "banana", "cherry")	#tuple	
x6 = range(6)	#range	
x7 = {"name" : "John", "age" : 36}	#dict	
x8 = {"apple", "banana", "cherry"}	#set	
x9 = frozenset({"apple", "banana", "cherry"})	#frozenset	
x10 = True	#bool	
x11 = b"Hello"	#bytes	
x12 = bytearray(5)	#bytearray	
x13 = memoryview(bytes(5))	#memoryview	
x14 = None	#NoneType	
